
// Objective-C API for talking to the following Go packages
//
//	github.com/adieu/flutter_go/go/plugin
//	github.com/adieu/flutter_go/go/channel
//	github.com/adieu/flutter_go/go/channel/types
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Plugin_FRAMEWORK_H__
#define __Plugin_FRAMEWORK_H__

#include "Plugin.objc.h"
#include "Channel.objc.h"
#include "Types.objc.h"
#include "Universe.objc.h"

#endif
