// Objective-C API for talking to github.com/adieu/flutter_go/go/plugin Go package.
//   gobind -lang=objc github.com/adieu/flutter_go/go/plugin
//
// File is generated by gobind. Do not edit.

#ifndef __Plugin_H__
#define __Plugin_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void PluginBootstrap(void);

#endif
