// Objective-C API for talking to github.com/adieu/flutter_go/go/channel/types Go package.
//   gobind -lang=objc github.com/adieu/flutter_go/go/channel/types
//
// File is generated by gobind. Do not edit.

#ifndef __Types_H__
#define __Types_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol TypesChannel;
@class TypesChannel;
@protocol TypesManager;
@class TypesManager;
@protocol TypesReplier;
@class TypesReplier;

@protocol TypesChannel <NSObject>
- (BOOL)send:(NSData* _Nullable)p0 p1:(id<TypesReplier> _Nullable)p1 error:(NSError* _Nullable* _Nullable)error;
@end

@protocol TypesManager <NSObject>
- (id<TypesChannel> _Nullable)newChannel:(NSString* _Nullable)p0 error:(NSError* _Nullable* _Nullable)error;
@end

@protocol TypesReplier <NSObject>
- (BOOL)reply:(NSData* _Nullable)p0 error:(NSError* _Nullable* _Nullable)error;
@end

@class TypesChannel;

@class TypesManager;

@class TypesReplier;

@interface TypesChannel : NSObject <goSeqRefInterface, TypesChannel> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)send:(NSData* _Nullable)p0 p1:(id<TypesReplier> _Nullable)p1 error:(NSError* _Nullable* _Nullable)error;
@end

@interface TypesManager : NSObject <goSeqRefInterface, TypesManager> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (id<TypesChannel> _Nullable)newChannel:(NSString* _Nullable)p0 error:(NSError* _Nullable* _Nullable)error;
@end

@interface TypesReplier : NSObject <goSeqRefInterface, TypesReplier> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)reply:(NSData* _Nullable)p0 error:(NSError* _Nullable* _Nullable)error;
@end

#endif
