// Objective-C API for talking to github.com/adieu/flutter_go/go/channel Go package.
//   gobind -lang=objc github.com/adieu/flutter_go/go/channel
//
// File is generated by gobind. Do not edit.

#ifndef __Channel_H__
#define __Channel_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Types.objc.h"

FOUNDATION_EXPORT id<TypesChannel> _Nullable ChannelConnect(NSString* _Nullable name, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL ChannelInit(id<TypesManager> _Nullable manager, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL ChannelSend(NSString* _Nullable name, NSData* _Nullable message, id<TypesReplier> _Nullable replier, NSError* _Nullable* _Nullable error);

#endif
